const json = (data, status=200) => new Response(JSON.stringify(data), {status, headers:{'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-headers':'content-type,authorization','access-control-allow-methods':'GET,POST,PUT,OPTIONS'}});
const now=()=>Date.now();
const id=()=>crypto.randomUUID();
const enc=new TextEncoder();
async function sha256(s){const b=await crypto.subtle.digest('SHA-256',enc.encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function secretCipher(text,secret){const raw=await crypto.subtle.digest('SHA-256',enc.encode(secret));const key=await crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt']);const iv=crypto.getRandomValues(new Uint8Array(12));const c=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(text));return btoa(String.fromCharCode(...iv,...new Uint8Array(c)));}
function body(r){return r.json().catch(()=>({}));}
async function user(r,env){const h=r.headers.get('authorization')||'';const token=h.startsWith('Bearer ')?h.slice(7):'';if(!token)return null;const s=await env.DB.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>?').bind(token,now()).first();return s||null;}
const fee=p=>p<100000?1000:p<1000000?2500:5000;
async function route(r,env){const u=new URL(r.url),p=u.pathname,m=r.method;
 if(m==='OPTIONS')return json({ok:true});
 if(p==='/api/health')return json({ok:true,service:'Velora Backend v9',db:'D1'});
 if(p==='/api/auth/register'&&m==='POST'){const b=await body(r);if(!b.email||!b.password||!b.name)return json({error:'name,email,password wajib'},400);if(!/^[^@\s]+@gmail\.com$/i.test(b.email))return json({error:'Gunakan Gmail untuk akun login'},400);const exists=await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(b.email.toLowerCase()).first();if(exists)return json({error:'Email sudah terdaftar'},409);const uid=id(), hash=await sha256(uid+':'+b.password);await env.DB.prepare('INSERT INTO users(id,email,name,password_hash,created_at) VALUES(?,?,?,?,?)').bind(uid,b.email.toLowerCase(),b.name,hash,now()).run();return json({ok:true});}
 if(p==='/api/auth/login'&&m==='POST'){const b=await body(r);const u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind((b.email||'').toLowerCase()).first();if(!u)return json({error:'Email/password salah'},401);const hash=await sha256(u.id+':'+(b.password||''));if(hash!==u.password_hash)return json({error:'Email/password salah'},401);const token=id()+id().replaceAll('-',''), exp=now()+30*24*3600*1000;await env.DB.prepare('INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)').bind(token,u.id,exp).run();return json({token,user:{id:u.id,email:u.email,name:u.name,role:u.role,verified:!!u.verified,balance:u.balance}});}
 const me=await user(r,env);if(!me)return json({error:'Unauthorized'},401);
 if(p==='/api/me')return json({user:{id:me.id,email:me.email,name:me.name,role:me.role,verified:!!me.verified,balance:me.balance}});
 if(p==='/api/products'&&m==='GET'){const q=(u.searchParams.get('q')||'').toLowerCase();let sql='SELECT p.*,u.name seller_name FROM products p JOIN users u ON u.id=p.seller_id WHERE p.active=1';const args=[];if(q){sql+=' AND lower(p.title||\' \'||p.game||\' \'||p.description||\' \'||u.name) LIKE ?';args.push('%'+q+'%');}sql+=' ORDER BY p.created_at DESC LIMIT 100';const rows=await env.DB.prepare(sql).bind(...args).all();return json({products:rows.results});}
 if(p==='/api/products'&&m==='POST'){if(me.role!=='seller'&&me.role!=='admin')return json({error:'Seller only'},403);const b=await body(r);const pid=id();await env.DB.prepare('INSERT INTO products(id,seller_id,title,game,description,price,created_at) VALUES(?,?,?,?,?,?,?)').bind(pid,me.id,b.title,b.game,b.description||'',Number(b.price),now()).run();return json({id:pid});}
 if(p==='/api/transactions'&&m==='POST'){const b=await body(r);const prod=await env.DB.prepare('SELECT * FROM products WHERE id=? AND active=1').bind(b.productId).first();if(!prod)return json({error:'Produk tidak ditemukan'},404);if(prod.seller_id===me.id)return json({error:'Tidak bisa membeli produk sendiri'},400);const f=fee(prod.price),tid=id();await env.DB.prepare('INSERT INTO transactions(id,buyer_id,seller_id,product_id,title,price,fee,total,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(tid,me.id,prod.seller_id,prod.id,prod.title,prod.price,f,prod.price+f,now()).run();await env.DB.prepare('INSERT INTO messages(id,room_id,uid,name,role,text,created_at) VALUES(?,?,?,?,?,?,?)').bind(id(),tid,me.id,me.name,me.role,'Transaksi dibuat. Group buyer + seller + admin aktif.',now()).run();return json({id:tid,fee:f,total:prod.price+f,status:'waiting_payment'});}
 if(p==='/api/transactions'&&m==='GET'){const rows=await env.DB.prepare('SELECT * FROM transactions WHERE buyer_id=? OR seller_id=? ORDER BY created_at DESC').bind(me.id,me.id).all();return json({transactions:rows.results});}
 const tm=p.match(/^\/api\/transactions\/([^/]+)\/messages$/);if(tm&&m==='GET'){const t=await env.DB.prepare('SELECT * FROM transactions WHERE id=? AND (buyer_id=? OR seller_id=? OR ?=\'admin\')').bind(tm[1],me.id,me.id,me.role).first();if(!t)return json({error:'Forbidden'},403);const rows=await env.DB.prepare('SELECT * FROM messages WHERE room_id=? ORDER BY created_at ASC').bind(tm[1]).all();return json({messages:rows.results});}
 if(tm&&m==='POST'){const t=await env.DB.prepare('SELECT * FROM transactions WHERE id=? AND (buyer_id=? OR seller_id=? OR ?=\'admin\')').bind(tm[1],me.id,me.id,me.role).first();if(!t)return json({error:'Forbidden'},403);const b=await body(r);const mid=id();await env.DB.prepare('INSERT INTO messages(id,room_id,uid,name,role,text,created_at) VALUES(?,?,?,?,?,?,?)').bind(mid,tm[1],me.id,me.name,me.role,b.text||'',now()).run();return json({id:mid});}
 const del=p.match(/^\/api\/transactions\/([^/]+)\/delivery$/);if(del&&m==='POST'){const t=await env.DB.prepare('SELECT * FROM transactions WHERE id=? AND seller_id=?').bind(del[1],me.id).first();if(!t)return json({error:'Seller only'},403);if(t.status!=='payment_verified')return json({error:'Pembayaran belum diverifikasi admin'},400);const b=await body(r);if(!/^[^@\s]+@gmail\.com$/i.test(b.email||''))return json({error:'Email akun wajib Gmail'},400);const cipher=await secretCipher(JSON.stringify({email:b.email,password:b.password}),env.DELIVERY_SECRET);await env.DB.prepare('INSERT OR REPLACE INTO deliveries(transaction_id,email,password_cipher,created_at) VALUES(?,?,?,?)').bind(t.id,b.email,cipher,now()).run();await env.DB.prepare('UPDATE transactions SET status=\'delivered\' WHERE id=?').bind(t.id).run();return json({ok:true});}
 if(p==='/api/withdrawals'&&m==='POST'){if(me.role!=='seller')return json({error:'Seller only'},403);const b=await body(r),amt=Number(b.amount);if(amt<10000||amt>me.balance)return json({error:'Nominal tidak valid'},400);const wid=id();await env.DB.prepare('INSERT INTO withdrawals(id,seller_id,amount,method,destination,created_at) VALUES(?,?,?,?,?,?)').bind(wid,me.id,amt,b.method,b.destination,now()).run();return json({id:wid,status:'requested'});}
 return json({error:'Not found'},404);
}
export default {async fetch(request,env){try{return await route(request,env)}catch(e){return json({error:'Server error',detail:String(e)},500)}}};
