name = "velora-backend"
main = "index.js"
compatibility_date = "2026-09-30"

[[d1_databases]]
binding = "DB"
database_name = "velora"
database_id = "
Current Version ID: 45c00bde-f853-4481-9e8d-90f736de0548"
